KEY_VARIABLES = ["Patient_ID", "Timestamp"]

HOSPITAL_STAY_VARIABLES = [
    "Length_of_Stay",
    "Admission_Mode",
    #"Discharge_Mode",
    "Visit_Type",
    "Admission_Unit",
    "Admission_Department",
    #"Discharge_Unit",
    #"Discharge_Department",
    "Emergency_Admission",
    "Number_of_Visited_Departments",
    "Visited_Units",
    "Visited_Departments",
]

PATIENT_VARIABLES = ["Gender", "Age"]

CONTEXTUAL_VARIABLES = [
    #"Rehabilitation_Discharge",
    "Cholesterol",
    "Smoking",
    "Alcohol_Use",
    "Sleep_Apnea",
    "Anticoagulant_Therapy",
    "Antiplatelet_Therapy",
    "Hypertension_ICA",
    "Hypertension_BETA",
    "Hypertension_TZD",
    "Hypertension_ARA",
    "Hypertension_IEC",
    "Hormonal_Therapy",
    "Diabetes_Med",
    "Cholesterol_Med",
    "Myocardial_Infarction",
    "Family_History",
    "Fisher_Score",
    "WFNS_Score",
    "Hypertension",
    "Diabetes",
    "Gout",
    "Glasgow_Coma_Scale",
    "Outcome",
] + HOSPITAL_STAY_VARIABLES + PATIENT_VARIABLES


SEQUENTIAL_VARIABLES = [
    "Headache",
    "Seizure",
    "Stress_Cardiomyopathy",
    "Cerebral_Salt_Wasting_Syndrome",
    "Vasospasm",
    "Hydrocephalus",
    "External_Ventricular_Drain_Details",
    "Intraventricular_Hemorrhage",
    "Delayed_Cerebral_Ischemia",
    "Low_Glucose",
    "High_Glucose",
    "Normal_Glucose",
    "Oxygen_Desaturation",
    "Low_BP",
    "High_BP",
    "Normal_BP",
    "Fever",
    "Weight",
    "Glasgow_Coma_Scale_Temporal",
    "Nimodipine",
    "Paracetamol",
    "Norepinephrine",
    "Milrinone",
    "Morphine",
    "Antiepileptic_Treatment",
    "Antiepileptic_Treatment_SAH",
    "Diagnosis",
    "External_Ventricular_Drain",
    "Ventriculoperitoneal_Shunt",
    "Angioplasty",
    "Orotracheal_Intubation",
    "Intracranial_Aneurysm_Treatment",
    "Normal_Sodium",
    "High_Sodium",
    "Low_Sodium",
    "Low_Oxygen_BP",
    "Anemia",
]